---

name: Code checks

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup lua toolchain
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 'luajit-2.1.0-beta3'

      - name: Setup lua toolchain
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install luacheck
        run: |
          luarocks install luacheck

      - name: Run luacheck
        run: |
          luacheck lua
